package kocfdunit.kocfdproject.kocfdpackage;

/**
 * This class was automatically generated by the data modeler tool.
 */


@javax.persistence.Entity
public class OptimizationDO implements java.io.Serializable
{
   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "OPTIMIZATIONDO_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "OPTIMIZATIONDO_ID_GENERATOR", sequenceName = "OPTIMIZATIONDO_ID_SEQ")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Ticket Id")
   private java.lang.Long ticketId;

   @org.kie.api.definition.type.Label("Ticket Sub Category")
   private java.lang.String ticketSubCategory;

   @org.kie.api.definition.type.Label("Well")
   private java.lang.String well;

   @org.kie.api.definition.type.Label("Field")
   private java.lang.String field;

   @org.kie.api.definition.type.Label("GC")
   private java.lang.String gc;

   @org.kie.api.definition.type.Label("Engineer")
   private java.lang.String engineer;

   @org.kie.api.definition.type.Label("Well Type")
   private java.lang.String wellType;

   @org.kie.api.definition.type.Label("Action Description")
   private java.lang.String action;

   @org.kie.api.definition.type.Label("Est. Production Change")
   private java.lang.Integer estProductionChange;

   @javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Label("Attachments")
   private java.util.List<java.lang.String> attachment;

   private java.lang.Integer oilGains;

   private java.lang.String fieldid;

   private java.lang.String gcid;

   private java.lang.String priority;

   private java.util.Date targetdate;

   private java.lang.Integer wellid;

   @org.kie.api.definition.type.Label(value = "WorkFlowCategory")
   private java.lang.String workFlowCategory;

   public OptimizationDO()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.Long getTicketId()
   {
      return this.ticketId;
   }

   public void setTicketId(java.lang.Long ticketId)
   {
      this.ticketId = ticketId;
   }

   public java.lang.String getTicketSubCategory()
   {
      return this.ticketSubCategory;
   }

   public void setTicketSubCategory(java.lang.String ticketSubCategory)
   {
      this.ticketSubCategory = ticketSubCategory;
   }

   public java.lang.String getWell()
   {
      return this.well;
   }

   public void setWell(java.lang.String well)
   {
      this.well = well;
   }

   public java.lang.String getField()
   {
      return this.field;
   }

   public void setField(java.lang.String field)
   {
      this.field = field;
   }

   public java.lang.String getGc()
   {
      return this.gc;
   }

   public void setGc(java.lang.String gc)
   {
      this.gc = gc;
   }

   public java.lang.String getEngineer()
   {
      return this.engineer;
   }

   public void setEngineer(java.lang.String engineer)
   {
      this.engineer = engineer;
   }

   public java.lang.String getWellType()
   {
      return this.wellType;
   }

   public void setWellType(java.lang.String wellType)
   {
      this.wellType = wellType;
   }

   public java.lang.String getAction()
   {
      return this.action;
   }

   public void setAction(java.lang.String action)
   {
      this.action = action;
   }

   public java.lang.Integer getEstProductionChange()
   {
      return this.estProductionChange;
   }

   public void setEstProductionChange(java.lang.Integer estProductionChange)
   {
      this.estProductionChange = estProductionChange;
   }

   public java.util.List<java.lang.String> getAttachment()
   {
      return this.attachment;
   }

   public void setAttachment(java.util.List<java.lang.String> attachment)
   {
      this.attachment = attachment;
   }

   public java.lang.Integer getOilGains()
   {
      return this.oilGains;
   }

   public void setOilGains(java.lang.Integer oilGains)
   {
      this.oilGains = oilGains;
   }

   public java.lang.String getFieldid()
   {
      return this.fieldid;
   }

   public void setFieldid(java.lang.String fieldid)
   {
      this.fieldid = fieldid;
   }

   public java.lang.String getGcid()
   {
      return this.gcid;
   }

   public void setGcid(java.lang.String gcid)
   {
      this.gcid = gcid;
   }

   public java.lang.String getPriority()
   {
      return this.priority;
   }

   public void setPriority(java.lang.String priority)
   {
      this.priority = priority;
   }

   public java.util.Date getTargetdate()
   {
      return this.targetdate;
   }

   public void setTargetdate(java.util.Date targetdate)
   {
      this.targetdate = targetdate;
   }

   public java.lang.Integer getWellid()
   {
      return this.wellid;
   }

   public void setWellid(java.lang.Integer wellid)
   {
      this.wellid = wellid;
   }

   public java.lang.String getWorkFlowCategory()
   {
      return this.workFlowCategory;
   }

   public void setWorkFlowCategory(java.lang.String workFlowCategory)
   {
      this.workFlowCategory = workFlowCategory;
   }

   public OptimizationDO(java.lang.Long id, java.lang.Long ticketId,
         java.lang.String ticketSubCategory, java.lang.String well,
         java.lang.String field, java.lang.String gc, java.lang.String engineer,
         java.lang.String wellType, java.lang.String action,
         java.lang.Integer estProductionChange,
         java.util.List<java.lang.String> attachment,
         java.lang.Integer oilGains, java.lang.String fieldid,
         java.lang.String gcid, java.lang.String priority,
         java.util.Date targetdate, java.lang.Integer wellid,
         java.lang.String workFlowCategory)
   {
      this.id = id;
      this.ticketId = ticketId;
      this.ticketSubCategory = ticketSubCategory;
      this.well = well;
      this.field = field;
      this.gc = gc;
      this.engineer = engineer;
      this.wellType = wellType;
      this.action = action;
      this.estProductionChange = estProductionChange;
      this.attachment = attachment;
      this.oilGains = oilGains;
      this.fieldid = fieldid;
      this.gcid = gcid;
      this.priority = priority;
      this.targetdate = targetdate;
      this.wellid = wellid;
      this.workFlowCategory = workFlowCategory;
   }

}
